### ISSUE TITLE
CI tests always fail on RtD

### ISSUE THREAD

**Issue by dHannasch** [pycontribs/ruyaml#38]
As seen at e.g. https://github.com/pycontribs/ruyaml/pull/35, the Read the Docs build always fails with `sphinx.errors.SphinxError: Source parser for ryd2rst not registered`.

```
Traceback (most recent call last):
  File "/home/docs/checkouts/readthedocs.org/user_builds/ruyaml/envs/35/lib/python3.7/site-packages/sphinx/registry.py", line 276, in get_source_parser
    return self.source_parsers[filetype]
KeyError: 'ryd2rst'

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/docs/checkouts/readthedocs.org/user_builds/ruyaml/envs/35/lib/python3.7/site-packages/sphinx/cmd/build.py", line 280, in build_main
    app.build(args.force_all, filenames)
  File "/home/docs/checkouts/readthedocs.org/user_builds/ruyaml/envs/35/lib/python3.7/site-packages/sphinx/application.py", line 352, in build
    self.builder.build_update()
  File "/home/docs/checkouts/readthedocs.org/user_builds/ruyaml/envs/35/lib/python3.7/site-packages/sphinx/builders/__init__.py", line 298, in build_update
    len(to_build))
  File "/home/docs/checkouts/readthedocs.org/user_builds/ruyaml/envs/35/lib/python3.7/site-packages/sphinx/builders/__init__.py", line 310, in build
    updated_docnames = set(self.read())
  File "/home/docs/checkouts/readthedocs.org/user_builds/ruyaml/envs/35/lib/python3.7/site-packages/sphinx/builders/__init__.py", line 417, in read
    self._read_serial(docnames)
  File "/home/docs/checkouts/readthedocs.org/user_builds/ruyaml/envs/35/lib/python3.7/site-packages/sphinx/builders/__init__.py", line 438, in _read_serial
    self.read_doc(docname)
  File "/home/docs/checkouts/readthedocs.org/user_builds/ruyaml/envs/35/lib/python3.7/site-packages/sphinx/builders/__init__.py", line 478, in read_doc
    doctree = read_doc(self.app, self.env, self.env.doc2path(docname))
  File "/home/docs/checkouts/readthedocs.org/user_builds/ruyaml/envs/35/lib/python3.7/site-packages/sphinx/io.py", line 190, in read_doc
    parser = app.registry.create_source_parser(app, filetype)
  File "/home/docs/checkouts/readthedocs.org/user_builds/ruyaml/envs/35/lib/python3.7/site-packages/sphinx/registry.py", line 284, in create_source_parser
    parser_class = self.get_source_parser(filename)
  File "/home/docs/checkouts/readthedocs.org/user_builds/ruyaml/envs/35/lib/python3.7/site-packages/sphinx/registry.py", line 278, in get_source_parser
    raise SphinxError(__('Source parser for %s not registered') % filetype) from exc
sphinx.errors.SphinxError: Source parser for ryd2rst not registered
```

This can apparently be resolved by https://github.com/pycontribs/ruyaml/pull/37. (I dunno *how*, because I really don't understand what's happening in that branch, but it passes.)

**Comment by smurfix** [comment]
We got rid of the .ryd files and the ryd-to-rst conversion.
